config/routes.rb
Rails.application.routes.draw do
  resources :premia
  get 'principal/inicio'

  root 'principal#inicio'

end

app/models/premium.rb
class Premium < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/premia_controller.rb
class PremiaController < ApplicationController
  before_action :set_premium, only: [:show, :edit, :update, :destroy]

  # GET /premia
  # GET /premia.json
  def index
    @premia = Premium.all
  end

  # GET /premia/1
  # GET /premia/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_premium
      @premium = Premium.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def premium_params
      params[:premium]
    end
end

app/controllers/principal_controller.rb
class PrincipalController < ApplicationController
  def inicio
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/premia_helper.rb
module PremiaHelper
end

app/helpers/principal_helper.rb
module PrincipalHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ggd</title>
  <link href="css/hover.css" rel="stylesheet" media="all">
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
</head>

<body>
	<%= render "shared/navbar"%>
	<%= yield %>
	<%= image_tag("tallercertificado.jpg", :style => " height:5%; position:fixed; bottom:0; right:0")%>
</body
</html>

app/views/premia/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Premium</title>
</head>
<body>
<img src="assets/eurovent.png">


</body>
</html>

app/views/premia/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_premium_path(@premium) %> |
<%= link_to 'Back', premia_path %>

app/views/principal/inicio.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
  form { display: inline; }
</style>
		<div class="container">
			<div class="jumbotron">
			  <h1>Aqui puedes encontrar todas las necesidades para tu casa </h1> 

			  <p style = "float:left";"display:inline";><a class="btn btn-primary btn-lg" href="#" role="button">Telefonos</a></p>			  
			  <p style = "float:right";"display:inline";>
			  <a class="btn btn-primary btn-lg" href="#" role="button">introduccion a los productos</a></p>
			  
			  <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d899.0618739746241!2d-100.3244296!3d25.6630892!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8662be22d6397e45%3A0x7d133f3e3e8c1735!2sCalle+16+de+Septiembre+907%2C+Independencia%2C+64720+Monterrey%2C+N.L.!5e0!3m2!1sen!2smx!4v1431492008159" width="100%" height="250" frameborder="0" style="border:0"></iframe>

			</div>
		</div>
	<title></title>
</head>
<body style="background-image:url(http://www.turnercostickers.com/ekmps/shops/turnerco/images/tree-landscape-3d-window-view-wall-art-sticker-16661-p.jpg)" width="100%" >

</body>
</html>

app/views/shared/_navbar.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/principal/inicio">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

      <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">premium
 <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="/premia">Ventanas</a></li>
            <li><a href="#">Puertas</a></li>
            <li><a href="#">Muro Cortina</a></li>
           
          </ul>

          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Eurovent <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">serie 50</a></li>
            <li class="divider"></li>
            <li><a href="#">serie 70</a></li>
            <li class="divider"></li>
            <li><a href="#">serie 60</a></li>
            
          </ul>  


        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Panorama <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>